# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

    allow:
      # Only allow major version updates to reduce noise from minor/patch updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

      # Allow minor versions for caf packages to ensure new versions are tested more often
      - dependency-name: "caf.*"
        update-types:
          - "version-update:semver-minor"

    # If you only want security update PRs, set this to 0
    open-pull-requests-limit: 3
